CREATE TABLE companies (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_name VARCHAR(255) NOT NULL,

    short_name VARCHAR(50) NOT NULL UNIQUE,

    company_email VARCHAR(255),

    company_phone VARCHAR(50),

    company_address TEXT,

    registration_number VARCHAR(100),

    industry VARCHAR(100),

    status VARCHAR(20) NOT NULL DEFAULT 'active',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);