CREATE TABLE users (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id INTEGER ,

    username VARCHAR(100) NOT NULL UNIQUE,

    email VARCHAR(255) NOT NULL UNIQUE,

    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(30) NOT NULL,

    phone_number VARCHAR(30),

    status VARCHAR(20) NOT NULL DEFAULT 'active',

    privilege_type VARCHAR(20) NOT NULL DEFAULT 'permanent',

    expires_at TIMESTAMP,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    last_login TIMESTAMP,

    last_seen TIMESTAMP,

    current_session_id UUID,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_company
        FOREIGN KEY(company_id)
        REFERENCES companies(id)
        ON DELETE SET NULL

);