CREATE TABLE leave_requests (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    request_number VARCHAR(100) UNIQUE NOT NULL,

    user_id INTEGER NOT NULL,

    company_id INTEGER NOT NULL,

    leave_type VARCHAR(50) NOT NULL,

    start_date DATE NOT NULL,

    end_date DATE NOT NULL,

    reason TEXT,

    attachment_url TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','approved','rejected','cancelled')),

    approved_by INTEGER,

    approved_at TIMESTAMP,

    rejected_reason TEXT,

    cancelled_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_leave_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_company
        FOREIGN KEY(company_id)
        REFERENCES companies(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leave_approved_by
        FOREIGN KEY(approved_by)
        REFERENCES users(id)
        ON DELETE SET NULL

);