CREATE TABLE audit_logs (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    actor_user_id INTEGER,

    actor_username VARCHAR(100),

    actor_role VARCHAR(50),

    company_id INTEGER,

    action VARCHAR(50) NOT NULL,

    target_type VARCHAR(50),

    target_id INTEGER,

    description TEXT NOT NULL,

    ip_address VARCHAR(100),

    user_agent TEXT,

    location VARCHAR(100),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_company
        FOREIGN KEY(company_id)
        REFERENCES companies(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_audit_actor
        FOREIGN KEY(actor_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL

);