name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e
            
            cd /home/ubuntu/react-mqtt-iot-dashboard

            echo "Reset local changes..."
            git reset --hard HEAD
            git clean -fd

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing backend dependencies..."
            cd backend
            npm install

            echo "Running production database migrations..."
            npm run migrate:production

            echo "Building frontend..."
            cd ../frontend
            npm install
            npm run build

            echo "Deploy frontend..."
            sudo rm -rf /var/www/novalobster/*
            sudo cp -r dist/* /var/www/novalobster/
            
            echo "Restarting backend..."
            cd ../backend
            pm2 restart backend

            echo "Deployment complete!"